import { useEffect, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowUpRight, Clock, MessageSquare, ShieldCheck } from 'lucide-react';
import { api, send } from './api';
import { useAuth } from './App';
import type { Posting } from './types';
import { Message } from './components';
export default function Account({contributions=false}:{contributions?:boolean}) {
  const {user,loading,refresh}=useAuth();const navigate=useNavigate();const [params]=useSearchParams();
  const [register,setRegister]=useState(false);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [posts,setPosts]=useState<Posting[]>([]);
  useEffect(()=>{if(user&&contributions)api<Posting[]>('/my-postings').then(setPosts).catch(e=>setError(e.message));},[user,contributions]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');try{await api(register?'/auth/register':'/auth/login',send('POST',Object.fromEntries(form)));await refresh();const next=params.get('next');navigate(next?.startsWith('/')&&!next.startsWith('//')?next:'/');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(loading)return <div className="page loading">Loading your account…</div>;
  if(contributions&&user)return <section className="page narrow"><span className="eyebrow">YOUR VOICE AT THE TABLE</span><h1>My contributions</h1><p className="muted">Follow your reviews, comments and company responses through moderation.</p><Message text={error} error/>{posts.length?posts.map(p=><article className="contribution" key={p.id}><div className="spread"><Link to={`/restaurants/${p.restaurant_id}`}>{p.restaurant_name}</Link><span className={`status ${p.status}`}>{p.status}</span></div><small>{p.kind} · {new Date(p.created_at).toLocaleDateString()}</small><p className="user-text" dir="auto">{p.body}</p>{p.status==='pending'&&<p className="field-hint"><Clock size={14}/> Waiting for moderator approval.</p>}{p.status==='rejected'&&<Message text={`Moderator’s note: ${p.moderation_reason}`}/>}</article>):<div className="empty"><MessageSquare size={32}/><h2>Your first review starts with a meal.</h2><Link className="button" to="/">Find a restaurant</Link></div>}</section>;
  if(user)return <div className="page narrow"><h1>You’re signed in, {user.name}.</h1><Link className="button" to="/">Explore restaurants</Link></div>;
  return <section className="account-page"><div className="account-story"><span className="eyebrow">PULL UP A CHAIR</span><h1>Good taste.<br/><em>Better together.</em></h1><p>A memorable meal deserves a story. Join the conversation and help someone find their next favourite.</p><div className="account-promise"><ShieldCheck/><span>Every contribution is moderated.<br/>Every voice has a place.</span></div></div><div className="account-form"><h2>{register?'Join the table':'Welcome back'}</h2><p className="muted">{register?'Create an account to share your food experiences.':'Sign in to share a review or manage your entries.'}</p><Message text={error} error/><form onSubmit={submit}>{register&&<label>Your name<input name="name" autoComplete="name" minLength={2} maxLength={80} required/></label>}<label>Email address<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>Password<input name="password" type="password" autoComplete={register?'new-password':'current-password'} minLength={register?12:1} maxLength={72} required/></label>{register&&<p className="field-hint">Use at least 12 characters (up to 72 UTF-8 bytes).</p>}<button className="button full" disabled={busy}>{busy?'Please wait…':register?'Create account':'Sign in'}<ArrowUpRight size={17}/></button></form><p className="account-switch">{register?'Already at the table?':'New here?'} <button className="text-button" onClick={()=>{setRegister(!register);setError('');}}>{register?'Sign in':'Create an account'}</button></p></div></section>;
}
