import { createContext, useContext, useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes, useNavigate } from 'react-router-dom';
import { Utensils, ArrowUpRight, LogOut, ShieldCheck, Menu as MenuIcon } from 'lucide-react';
import { api, appName, send } from './api';
import type { User } from './types';
import Explore from './Explore';
import RestaurantPage from './RestaurantPage';
import Admin from './Admin';
import Account from './Account';
import { Message } from './components';
type Auth={user:User|null;loading:boolean;refresh:()=>Promise<void>};
const AuthContext=createContext<Auth>({user:null,loading:true,refresh:async()=>{}});
export const useAuth=()=>useContext(AuthContext);
export default function App(){
  const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [menu,setMenu]=useState(false);const navigate=useNavigate();
  async function refresh(){try{setUser((await api<{user:User|null}>('/auth/me')).user);}finally{setLoading(false);}}
  useEffect(()=>{refresh().catch(()=>setError('Unable to connect. Check that the server is running.'));document.title=`${appName} · Discover your next favourite`;},[]);
  async function logout(){try{await api('/auth/logout',send('POST',{}));await refresh();navigate('/');}catch(e){setError((e as Error).message);}}
  return <AuthContext.Provider value={{user,loading,refresh}}><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="header-inner"><Link className="brand" to="/" aria-label={`${appName} home`}><span className="brand-mark"><Utensils size={22}/></span>{appName}<span className="brand-dot">.</span></Link><button className="mobile-menu icon-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><MenuIcon/></button><nav className={menu?'open':''} aria-label="Main navigation" onClick={()=>setMenu(false)}><NavLink to="/" end>Explore</NavLink><NavLink to="/how-it-works">How it works</NavLink>{user&&<NavLink to="/my-reviews">My contributions</NavLink>}{(user?.role==='admin'||user?.role==='moderator')&&<NavLink to="/admin"><ShieldCheck size={15}/>Dashboard</NavLink>}</nav><div className="account-nav">{user?<><span className="user-name">Hi, {user.name.split(' ')[0]}</span><button className="icon-button" aria-label="Sign out" onClick={logout}><LogOut size={18}/></button></>:<Link className="button small" to="/account">Sign in <ArrowUpRight size={16}/></Link>}</div></div></header><Message text={error} error/><main id="main"><Routes><Route path="/" element={<Explore/>}/><Route path="/restaurants/:id" element={<RestaurantPage/>}/><Route path="/account" element={<Account/>}/><Route path="/my-reviews" element={<Account contributions/>}/><Route path="/admin" element={<Admin/>}/><Route path="/how-it-works" element={<HowItWorks/>}/><Route path="*" element={<div className="page narrow"><h1>That page isn’t on the menu.</h1><Link className="button" to="/">Back to exploring</Link></div>}/></Routes></main><footer><Link className="brand" to="/"><Utensils size={18}/>{appName}.</Link><span>Colombo · Kandy · Galle</span><span>Prototype · Sample venues, prices & reviews</span></footer></AuthContext.Provider>;
}
function HowItWorks(){return <article className="page narrow prose"><span className="eyebrow">A seat at the table</span><h1>Find your flavour.</h1><p>Explore restaurants and dishes across Colombo, Kandy and Galle. Search in English, Sinhala or Tamil, then narrow your choices by cuisine, dietary preferences, spice level and budget.</p><h2>Know what’s on the menu</h2><p>Prices are shown in Sri Lankan rupees. Restaurant price bands use the average price of all their menu items: budget is below LKR 1,000; mid-range is LKR 1,000–2,500; premium is above LKR 2,500. This is a price per menu item, not a bill for a whole visit. Dietary filters must match the same dish. Halal labels are recorded preparation attributes, not independent certification.</p><h2>Reviews with a little more care</h2><p>Rate food quality, customer service, value for money and ambience from 1 to 5. Their equal-weight average is your restaurant score. If you select a dish, your food-quality score also contributes to that dish’s rating. Only approved reviews affect ratings.</p><p>“Recommended” balances ratings with review volume using (review count × average rating + 5 × 3.5) ÷ (review count + 5). “Highest rated” sorts by the displayed average. Restaurants without reviews show “New”.</p><h2>Every contribution gets reviewed</h2><p>Reviews, comments and company responses enter a moderation queue. A moderator must approve them before they appear here. Rejected content stays private, and you can see the reason in My contributions. Restaurant representatives can respond to reviews of their own establishments.</p><h2>About this prototype</h2><p>All restaurants, addresses, prices, reviews and dietary claims in the sample data are illustrative. Stock photographs represent food and dining; they are not photographs of these fictional venues or their exact dishes.</p><p>Our category choices draw on <a href="https://www.ubereats.com/lk/store/cafe-on-the-5th/WvNw41r0SEufnXpd5s6bNQ">Uber Eats’ Sri Lankan menus</a> and <a href="https://www.yamu.lk/trending/a-taste-of-jaffna-in-wellawatte/">YAMU’s coverage of Jaffna cuisine</a>. Photography: <a href="https://unsplash.com/photos/_WQ1qARALg4">Zoshua Colah</a>, <a href="https://unsplash.com/photos/JytWb3cFy40">litoon dev</a>, and <a href="https://www.pexels.com/photo/5607958/">cottonbro studio</a>.</p><Link className="button" to="/">Explore restaurants <ArrowUpRight size={16}/></Link></article>;}
