export type User = {
  id: number;
  name: string;
  email: string;
  role: 'customer' | 'owner' | 'admin' | 'moderator';
};
export type Category = { id: number; name: string; slug: string };
export type Restaurant = {
  id: number;
  name: string;
  city: string;
  address: string;
  description: string;
  image_url: string;
  owner_id: number | null;
  avg_price: string | null;
  min_price: string | null;
  max_price: string | null;
  price_band: string;
  menu_count: number;
  review_count: number;
  rating: string | null;
  rank_score: string;
  categories?: string[];
};
export type Dish = {
  id: number;
  restaurant_id: number;
  category_id: number;
  name: string;
  name_si: string;
  name_ta: string;
  description: string;
  price: string;
  image_url: string;
  vegetarian: boolean;
  vegan: boolean;
  halal: boolean;
  spice: number;
  category: string;
  category_slug: string;
  restaurant_name: string;
  city: string;
  rating: string | null;
  review_count: number;
};
export type Posting = {
  id: number;
  author_id?: number;
  author: string;
  restaurant_id: number;
  restaurant_name?: string;
  menu_item_id: number | null;
  dish_name?: string;
  kind: 'review' | 'comment' | 'response';
  body: string;
  parent_id: number | null;
  parent_body?: string;
  food: number;
  service: number;
  value: number;
  ambience: number;
  status?: string;
  moderation_reason?: string;
  created_at: string;
};
export type Detail = {
  restaurant: Restaurant;
  menu: Dish[];
  reviews: Posting[];
  breakdown: Record<string, string | null>;
};
